### ISSUE TITLE
Updating dashboard

### ISSUE THREAD

**Issue by iOut1aw** [angela-d/brain-dump#2]
Hi.

I see that PRTG Plugin 4.0.3 didnt update dashboards with Table visualization.
On v4.0.4 all works normal.

Did you saw tihs issue?

**Comment by angela-d** [comment]
By v4.0.4, are you referring to the master branch on Github?

The [latest version in the master branch](https://github.com/neuralfraud/grafana-prtg/blob/master/CHANGELOG.md) (tagged 4.0.4 in changelog) is broken for me.

For me, the Table visualization did not break, but Graphs did.  I am on the [development branch](https://github.com/neuralfraud/grafana-prtg/tree/Development) of the plugin right now.  One day soon I will test the master branch again, because I'd like the performance improvements.  I didn't really investigate when I seen the graphs break, I just switched back.

Edit: You've inspired me to trial it again.

So it appears my graphs' channel names changed!

**From:**
Traffic Total

**To:**
Traffic Total (volume)

With that mystery solved, I'm going to run through and do my customizations and I'll also be on v4.0.4

I'm also seeing a difference in calculations, so I'm going to tackle that as well.

**Comment by iOut1aw** [comment]
I have installed plugin from this link - https://github.com/neuralfraud/grafana-prtg/archive/master.zip

Have you checked updating Dashboards on Dev brach?
For me it is a critical because i need to monitoring internet channels on many offices.
On Dev brach updating is broken for me, it could be because of Cache updating.

But i need the Graphs too and they don't work on plugin linked upper, don't why.

**Comment by iOut1aw** [comment]
I dont know why, but now it's alive. Whats hapening here? :D

**Comment by angela-d** [comment]
When you first create a query, I find it doesn't take right away.  It takes a few seconds to "refresh" - perhaps not waiting long enough before?

Hoping the performance of that improves in future releases, I don't think that's a PRTG issue cause if you query the API directly (outside of Grafana) that delay isn't there.
